artifact_location: file:///c:/Users/jaswe/OneDrive/Desktop/opt/Projects/UnEmployment_Rate_Prediction/mlruns/0/models/m-a301c8d4662f46d5a287b279ca3231b4/artifacts
creation_timestamp: 1752093309719
experiment_id: '0'
last_updated_timestamp: 1752093312912
model_id: m-a301c8d4662f46d5a287b279ca3231b4
model_type: null
name: model
source_run_id: 9b2d1b2819e6403aaf1b6a7252c25e7d
status: 2
status_message: null
